### PR TITLE
update readme to spanish

### PR DESCRIPTION
**Pull request by ghost**
Update readme to Spanish.

This is related to the issue: _**Add Translation README.MD for Spanish #9**_

### CODE REVIEW

**Review by GeraAlcantara — CHANGES_REQUESTED** [review]
hi @samc18 
Instead of modifying the README.md can you please ad a README[ES_MX].md version

**Review by GeraAlcantara — APPROVED** [review]
Look great Thks

**Comment by GeraAlcantara** [comment]
great work !

**Comment by ghost** [comment]
thanks to you for creating these opportunities so people with different skill levels can participate as well!

**Pull request merged**
